---
# tasks file for myfirewall
- name: install firewall
  yum:
    name: firewalld
    state: latest
- name: start and enable firewalld service
  service:
    name: firewalld
    state: started
    enabled: true
- name: firewall service config
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    service: "{{ firewall_service }}"
