---
- name: install package
  hosts: intranetweb
  become: true
  vars:
    install_package:
    - httpd
    - haproxy
  tasks:
  - name: install package
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ install_package }}"
    when: install_package is defined
