---
- name: Install and start Apache HTTPS
  hosts: intranetweb 
  become: true
  vars:
    package_name: httpd
    service_name: httpd
  tasks:
  - name: install "{{ package_name }}" package
    yum:
      name: "{{ package_name }}"
      state: latest
  - name: start "{{ service_name }}" service
    service:
      name: "{{ service_name }}"
      state: started
      enabled: true
