---
- name: install httpd and restart service
  hosts: intranetweb
  become: true
  tasks:
  - name: install httpd server
    yum:
      name: httpd
      state: latest
  - name: start httpd server
    service:
      name: httpd
      state: started
      enabled: true
  - name: copy http file
    copy:
      src: content/index.html
      dest: /var/www/html/index.html
    notify: restart_httpd

  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restarted

